### ISSUE TITLE
#cpuError

### ISSUE THREAD

**Issue by epifaniofrancisco** [Vivaldo-Roque/TicTacToe#4]
Quando você escolhe escolher contra a CPU, se tu escolheres jogar com 'O' a CPU simplesmente te deixa ganhar várias vezes.

**Comment by Vivaldo-Roque** [comment]
Notei isso resolver já.
Se quiseres podes dar um uma olhada no código.

**Comment by Vivaldo-Roque** [comment]
Notei meu problema, eu esqueci de passar um argumento para minha função que acha o melhor movimento.

Antes => move = findBestMove(board);

Agora => move = findBestMove(board, user);

Não sei como fui esquecer isso.

**Comment by epifaniofrancisco** [comment]
Depois irei testar se está tudo resolvido
👍💻

A sábado, 26/03/2022, 21:05, Vivaldo Roque (Wython) <
***@***.***> escreveu:
